# Generated by Django 2.0 on 2020-10-28 17:36

import os

from django.contrib.auth.hashers import make_password
from django.db import migrations


def give_portaladmin_teacher_profile(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("common", "UserProfile")
    School = apps.get_model("common", "School")
    Teacher = apps.get_model("common", "Teacher")
    Class = apps.get_model("common", "Class")
    Student = apps.get_model("common", "Student")

    portaladmin = User.objects.get(username="portaladmin")
    portaladmin.first_name = "Portal"
    portaladmin.last_name = "Admin"
    portaladmin.email = "codeforlife-portal@ocado.com"
    portaladmin.save()
    portaladmin_userprofile = UserProfile.objects.create(user=portaladmin)
    portaladmin_school = School.objects.get(name="Swiss Federal Polytechnic")
    portaladmin_teacher = Teacher.objects.create(
        title="Mr",
        user=portaladmin_userprofile,
        new_user=portaladmin,
        school=portaladmin_school,
        is_admin=True,
        pending_join_request=None,
    )
    portaladmin_class = Class.objects.create(
        name="Portaladmin's class",
        teacher=portaladmin_teacher,
        access_code="PO123",
        classmates_data_viewable=True,
        always_accept_requests=True,
    )

    portaladmin_student_user = User.objects.create(
        username="portaladmin student",
        first_name="Portaladmin",
        last_name="Student",
        email="adminstudent@codeforlife.com",
        password=make_password(os.getenv("ADMIN_PASSWORD", "Password1")),
    )
    portaladmin_student_userprofile = UserProfile.objects.create(
        user=portaladmin_student_user
    )

    portaladmin_student = Student.objects.create(
        class_field=portaladmin_class,
        user=portaladmin_student_userprofile,
        pending_class_request=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0060_delete_guardian"),
    ]

    operations = [
        migrations.RunPython(code=give_portaladmin_teacher_profile),
    ]
