---
engines:
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
  radon:
    enabled: true
  scss-lint:
    enabled: true
    exclude_paths:
      - "**/*.css"
exclude_patterns:
  - "portal/_version.py"
  - "portal/static/portal/sass/bootstrap.scss"
  - "portal/static/portal/sass/bootstrap*/"
  - "portal/static/portal/css/bootstrap.css"
  - "portal/static/portal/js/lib/"
  - "portal/static/portal/js/bootstrap.js"
  - "portal/tests/"
  - "portal/migrations/"
  - "cfl_common/common/tests/"
  - "cfl_common/common/migrations/"
  - "example_project/"
  - "test_settings.py"
  - "**/*.eggs"
ratings:
  paths:
    - "**.css"
    - "**.js"
    - "**.py"
    - "**.scss"
