#!/bin/bash
source VIRTUALENV/bin/activate

python manage.py test game
GAMERESULT=$?

# python manage.py test portal
# PORTALRESULT=$?
PORTALRESULT=1

[ $GAMERESULT -ne 0 ] && [ $PORTALRESULT -ne 0 ] && exit 1
exit 0