# https://github.com/python-semantic-release/python-semantic-release/blob/v9/docs/configuration.rst
[semantic_release]
version_variables = ["portal/__init__.py:__version__"]
commit_message = "v{version} [skip ci]"

[semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
