#!/bin/bash
set -e
cd "${BASH_SOURCE%/*}"

./example_project/manage.py migrate --noinput --settings example_project.test_settings
./example_project/manage.py collectstatic --noinput --settings example_project.test_settings
./example_project/manage.py runserver "$@" --settings example_project.test_settings
