#!/bin/bash
set -e
cd "${BASH_SOURCE%/*}"

pushd portal_frontend
yarn --frozen-lockfile
yarn build
mv build ../portal/frontend
popd

./example_project/manage.py migrate --noinput
./example_project/manage.py collectstatic --noinput
./example_project/manage.py runserver "$@"
