#!/bin/bash
set -e
cd "${BASH_SOURCE%/*}"

./example_project/manage.py collectstatic --noinput --settings example_project.test_settings
./example_project/manage.py testserver portal/tests/cypress/fixtures/teachersToBeDeleted.json --settings example_project.test_settings
