#!/bin/bash
set -e
cd "${BASH_SOURCE%/*}"

./manage.py collectstatic --noinput --clear
./manage.py testserver \
  portal/cfl_common/common/fixtures/seed.json \
  portal/tests/cypress/fixtures/teachersToBeDeleted.json \
  --settings="example_project.portal_test_settings"
