# Generated by Django 5.2.11 on 2026-02-04 16:52

import common.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("access_code", models.CharField(max_length=5, null=True)),
                ("classmates_data_viewable", models.BooleanField(default=False)),
                ("always_accept_requests", models.BooleanField(default=False)),
                ("accept_requests_until", models.DateTimeField(null=True)),
                ("creation_time", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "classes",
            },
        ),
        migrations.CreateModel(
            name="DailyActivity",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("csv_click_count", models.PositiveIntegerField(default=0)),
                ("login_cards_click_count", models.PositiveIntegerField(default=0)),
                ("primary_coding_club_downloads", models.PositiveIntegerField(default=0)),
                ("python_coding_club_downloads", models.PositiveIntegerField(default=0)),
                ("level_control_submits", models.PositiveBigIntegerField(default=0)),
                ("teacher_lockout_resets", models.PositiveIntegerField(default=0)),
                ("indy_lockout_resets", models.PositiveIntegerField(default=0)),
                ("school_student_lockout_resets", models.PositiveIntegerField(default=0)),
                ("anonymised_unverified_teachers", models.PositiveIntegerField(default=0)),
                ("anonymised_unverified_independents", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Daily activities",
            },
        ),
        migrations.CreateModel(
            name="DynamicElement",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(editable=False, max_length=64, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("text", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True)),
                ("country", django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ("county", models.CharField(blank=True, max_length=50, null=True)),
                ("creation_time", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TotalActivity",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("teacher_registrations", models.PositiveIntegerField(default=0)),
                ("student_registrations", models.PositiveIntegerField(default=0)),
                ("independent_registrations", models.PositiveIntegerField(default=0)),
                ("anonymised_unverified_teachers", models.PositiveIntegerField(default=0)),
                ("anonymised_unverified_independents", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Total activity",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("login_id", models.CharField(max_length=64, null=True)),
                ("blocked_time", models.DateTimeField(blank=True, null=True)),
                (
                    "class_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="common.class",
                    ),
                ),
                (
                    "new_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pending_class_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_request",
                        to="common.class",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JoinReleaseStudent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action_type", models.CharField(max_length=64)),
                ("action_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="student", to="common.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_admin", models.BooleanField(default=False)),
                ("blocked_time", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_teachers",
                        to="common.teacher",
                    ),
                ),
                (
                    "new_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_teacher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_school",
                        to="common.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolTeacherInvitation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(max_length=88)),
                ("invited_teacher_first_name", models.CharField(max_length=150)),
                ("_invited_teacher_first_name", models.BinaryField(blank=True, null=True)),
                ("invited_teacher_last_name", models.CharField(max_length=150)),
                ("_invited_teacher_last_name", models.BinaryField(blank=True, null=True)),
                ("invited_teacher_email", models.EmailField(max_length=254)),
                ("_invited_teacher_email", models.BinaryField(blank=True, null=True)),
                ("invited_teacher_is_admin", models.BooleanField(default=False)),
                ("expiry", models.DateTimeField()),
                ("creation_time", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_invitations",
                        to="common.school",
                    ),
                ),
                (
                    "from_teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_invitations",
                        to="common.teacher",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="class",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_classes",
                to="common.teacher",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="class_teacher", to="common.teacher"
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("otp_secret", models.CharField(blank=True, max_length=40, null=True)),
                ("last_otp_for_time", models.DateTimeField(blank=True, null=True)),
                ("developer", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("first_name", models.CharField(blank=True, max_length=200, null=True)),
                ("_first_name", models.BinaryField(blank=True, null=True)),
                ("last_name", models.CharField(blank=True, max_length=200, null=True)),
                ("_last_name", models.BinaryField(blank=True, null=True)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
                ("_email", models.BinaryField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=200, null=True)),
                ("_username", models.BinaryField(blank=True, null=True)),
                ("google_refresh_token", common.models.EncryptedCharField(blank=True, max_length=1004, null=True)),
                ("google_sub", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="common.userprofile"),
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="common.userprofile"),
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("login_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("login_type", models.CharField(max_length=100, null=True)),
                (
                    "class_field",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="common.class"),
                ),
                (
                    "school",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="common.school"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="teacher",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_admin", True), ("school__isnull", True), _negated=True),
                name="teacher__is_admin",
            ),
        ),
    ]
