# Generated by Django 5.2.11 on 2026-02-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DynamicElement",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(editable=False, max_length=64, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("text", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
