# Generated by Django 2.2.20 on 2021-04-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_unlock_worksheet_3'),
        ('portal', '0058_move_to_common_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blocked_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='blocked_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
