# Generated by Django 3.2.12 on 2022-04-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_copy_email_to_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kurono_badges',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
