# Generated by Django 2.2.26 on 2022-03-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_update_aimmo_character_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimmocharacter',
            name='alt',
            field=models.TextField(max_length=255),
        ),
    ]
