# Generated by Django 2.2.26 on 2022-03-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20220317_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimmocharacter',
            name='alt',
        ),
    ]
