# Generated by Django 2.2.26 on 2022-03-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_remove_aimmocharacter_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimmocharacter',
            name='alt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
