# Generated by Django 3.2.12 on 2022-05-05 10:25

from django.db import migrations
from django.db.models import Q, Exists, OuterRef

from ..utils import anonymise


def anonymise_orphan_schools_and_classes(apps, schema_editor):
    # print("\n\n")
    School = apps.get_model("common", "School")
    Class = apps.get_model("common", "Class")
    Teacher = apps.get_model("common", "Teacher")
    # for school in School.objects.filter(teacher_school=None):
    # Filter to schools with no active teachers
    for school in School.objects.filter(
        Exists(
            Teacher.objects.filter(school=OuterRef("pk"), new_user__is_active=True),
            negated=True,
        )
    ):
        # school.anonymise()
        print(school)
    classes = Class.objects.filter(teacher__new_user__is_active=False)
    for class_ in classes:
        for student in class_.students.all():
            # anonymise(student.new_user)
            print(student)
        # class_.anonymise()
        print(class_)


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0022_school_cleanup"),
    ]

    operations = [
        migrations.RunPython(
            anonymise_orphan_schools_and_classes, reverse_code=migrations.RunPython.noop
        )
    ]
