# Generated by Django 3.2.13 on 2022-05-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_school_cleanup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
    ]
