# Generated by Django 3.2.16 on 2023-01-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_improve_admin_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='daily_indy_lockout_reset',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='daily_teacher_lockout_reset',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
