# Generated by Django 3.2.16 on 2022-12-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_improve_admin_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='rapid_router_access_settings',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
