# Generated by Django 3.2.16 on 2023-01-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0032_dailyactivity_level_control_submits"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyactivity",
            name="daily_indy_lockout_reset",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyactivity",
            name="daily_teacher_lockout_reset",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
