# Generated by Django 3.2.25 on 2024-05-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0051_verify_returning_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolteacherinvitation',
            name='_invited_teacher_email',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolteacherinvitation',
            name='_invited_teacher_first_name',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolteacherinvitation',
            name='_invited_teacher_last_name',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_email',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_first_name',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_last_name',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_username',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
