# Generated by Django 3.2.25 on 2024-07-31 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0053_clean_class_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AimmoCharacter',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='aimmo_badges',
        ),
    ]
