# Generated by Django 3.2.25 on 2024-09-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0054_delete_aimmo_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolteacherinvitation',
            name='token',
            field=models.CharField(max_length=88),
        ),
    ]
