# Generated by Django 4.2.17 on 2025-01-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0056_set_non_school_teachers_as_non_admins"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="teacher",
            constraint=models.CheckConstraint(
                check=models.Q(("is_admin", True), ("school__isnull", True), _negated=True), name="teacher__is_admin"
            ),
        ),
    ]
