# Generated by Django 5.1.10 on 2025-08-12 12:51

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0057_teacher_teacher__is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="google_refresh_token",
            field=common.models.EncryptedCharField(blank=True, max_length=1004, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="google_sub",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
