# Generated by Django 5.2.11 on 2026-02-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0058_userprofile_google_refresh_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="_email",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="_first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="_last_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="_username",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="google_refresh_token",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="google_sub",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="username",
        ),
    ]
