name: Check PR author

on:
  pull_request:

jobs:
  check-user:
    name: Team affiliation
    runs-on: ubuntu-latest
    steps:
      - name: Check user for team affiliation
        uses: tspascoal/get-user-teams-membership@v2
        id: teamAffiliation
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.actor }}
          team: codeforlife
      - name: Stop workflow if user is no member
        if: ${{ steps.teamAffiliation.outputs.isTeamMember == false }}
        run: |
          echo "You have no rights to trigger this job."
          exit 1
