name: Check PR author

on:
  pull_request:

jobs:
  check-member:
    runs-on: ubuntu-latest
    name: Check if an user exists
    steps:
      - name: Check if member exists
        id: check-member
        uses: bryantson/check-member-exists-in-team-actions@1.0
        with:
          team_slug: codeforlife
          org_slug: ocadotechnology
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.event.pull_request.user.login }}

      - name: Print whether member exists
        run: |
          echo "Does member exists: ${{ steps.check-member.outputs.exists-in-team }}"

      - name: Trigger verification workflow if user is not member
        if: ${{ steps.teamAffiliation.outputs.isTeamMember == false }}
        run: | # or 'uses' if using an action
        # Trigger verification workflow
