name: Publish PyPi packages
on:
  workflow_run:
    workflows: ["CI"]
    branches: [github_actions_publish_pypi]
    types:
      - completed
jobs:
  publish-pypi-packages:
    name: 🐍
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Set up Python 3.6.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.7
      - name: Setup git username
        run: |
          git config --global user.name "semantic-release (via Github Actions)"
          git config --global user.email "semantic-release@github-actions"
      - name: Release codeforlife-portal
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}
      - name: Publish cfl-common PyPi package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: cfl_common/
          skip_existing: true
        

