name: Saucelabs
on:
    release:
        types: [published]
    pull_request:
jobs:
    test:
        runs-on: ubuntu-latest
        name: Action Test
        steps:
            - uses: saucelabs/sauce-connect-action@v2
              with:
                  username: ${{ secrets.SAUCE_USERNAME }}
                  accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
                  tunnelName: OSP-core
                  configFile: ./config.yaml
